#!/bin/bash

# Script Name:                  Ops-Challenge #09
# Author:                       Wayne Brandon
# Date of latest revision:      05/04/2023
# Purpose:                      Educational (PowerShell scripting)

# Declaration of variables

# Declaration of functions
# Gets the events in an event log, or a list of the event logs, on the local or remote computers.

get-eventlog -logname system -after(get-date).adddays(-1) | out-file $home\desktop\systemloglast-24.txt
# Main

#Output all “error” type events from the System event log to a file on your desktop named errors.txt.
get-eventlog -logname system -entrytype error | out-file $home\desktop\systemerrorlog.txt


#Print to the screen all events with ID of 16 from the System event log.
get-eventlog -logname system -instanceID 16



#Print to the screen the most recent 20 entries from the System event log.
get-eventlog -logname system -newest 20


#Print to the screen all sources of the 500 most recent entries in the System event log. 
#Ensure that the full lines are displayed (get rid of the … and show the entire text).
get-eventlog -logname system -newest 500 | format-table * -wrap


# End
